"""add_company_id_to_opportunities_make_lead_nullable

Revision ID: 0d2d393eedf7
Revises: 772922f17577
Create Date: 2026-08-31 02:56:16.198619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d2d393eedf7'
down_revision: Union[str, Sequence[str], None] = '772922f17577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('company_id', sa.Integer(), nullable=False))
    op.alter_column('opportunities', 'lead_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('ix_opportunities_company_id', 'opportunities', ['company_id'], unique=False)
    op.drop_constraint(op.f('opportunities_lead_id_fkey'), 'opportunities', type_='foreignkey')
    op.create_foreign_key(None, 'opportunities', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'opportunities', 'leads', ['lead_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'opportunities', type_='foreignkey')
    op.drop_constraint(None, 'opportunities', type_='foreignkey')
    op.create_foreign_key(op.f('opportunities_lead_id_fkey'), 'opportunities', 'leads', ['lead_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_opportunities_company_id', table_name='opportunities')
    op.alter_column('opportunities', 'lead_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('opportunities', 'company_id')
    # ### end Alembic commands ###
