"""add_campaign_opportunities_association

Revision ID: 4566393fef95
Revises: 0d2d393eedf7
Create Date: 2026-08-31 18:13:14.964172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4566393fef95'
down_revision: Union[str, Sequence[str], None] = '0d2d393eedf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'opportunity_id', name='uq_campaign_opportunity')
    )
    op.create_index('ix_campaign_opportunities_campaign_id', 'campaign_opportunities', ['campaign_id'], unique=False)
    op.create_index('ix_campaign_opportunities_opportunity_id', 'campaign_opportunities', ['opportunity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_campaign_opportunities_opportunity_id', table_name='campaign_opportunities')
    op.drop_index('ix_campaign_opportunities_campaign_id', table_name='campaign_opportunities')
    op.drop_table('campaign_opportunities')
    # ### end Alembic commands ###
